name: Build and Upload RPM

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Runs a community action
    - name: Build RPM 
      id: rpm
      uses: naveenrajm7/rpmbuild@master
      with:
        spec_file: "bello.spec"
    
    - name: Check output
      run: echo ${{ steps.rpm.outputs.source_rpm_path }}
    
    - name: Upload RPM
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Binary RPM 
        path: ${{ steps.rpm.outputs.rpm_dir_path }}
